version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    hostname: mssql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Root1234!
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - db-network
    restart: unless-stopped

  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: cloudbeaver
    ports:
      - "8978:8978"
    volumes:
      - cloudbeaver_data:/opt/cloudbeaver/workspace
    networks:
      - db-network
    depends_on:
      - mssql
    restart: unless-stopped

networks:
  db-network:
    driver: bridge

volumes:
  mssql_data:
  cloudbeaver_data: