worker_processes auto;

events {
    worker_connections 10240;
    multi_accept on;
}

http {
    log_format my_upstream '{"timestamp": "$time_iso8601", "x-tuid": "$http_x_tuid","request": "$request", "status": "$status", "http_user_agent": "$http_user_agent", "X-Client-Cert-Subject": "$http_x_client_cert_subject","X-Client-Cert": "$http_x_client_cert", "host": "$host", "remote_addr": "$remote_addr","proxy_add_x_forwarded_for": "$proxy_add_x_forwarded_for"}';
    error_log /dev/stdout debug;
    access_log /dev/stdout my_upstream;
    default_type  application/octet-stream;

    sendfile        on;
    tcp_nopush      on;
    tcp_nodelay     on;
    keepalive_timeout  65;
    client_max_body_size 10m;

    upstream backend_individual {
        server individual-mock:8443;
        keepalive 1024;
    }

    upstream backend_commercial {
        server commercial-mock:8443;
        keepalive 1024;
    }

    map $http_user_agent $is_browser {
    default 0;
    ~*ozilla 1;
    ~*hrome 1;
    ~*pera 1;
    }

    server {
        listen 8080;
        listen 8443;
        server_name localhost;
        proxy_ssl_verify off;
        proxy_ssl_server_name on;
        ssl_protocols TLSv1.2 TLSv1.3;
        proxy_ssl_trusted_certificate /etc/ssl/certs/ca-certificates.crt;
        add_header Content-Security-Policy "default-src 'self'; frame-ancestors 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' 'unsafe-inline' blob: data: 'unsafe-eval';";
        add_header X-XSS-Protection "1; mode=block" always;
        add_header X-Content-Type-Options nosniff;
        add_header X-Frame-Options SAMEORIGIN;
        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
        proxy_cookie_flags / "/; HTTPOnly; Secure SameSite=none";
        location = /error.html {
            root /usr/share/nginx/html;
            internal;
        }
        location = /auth/ {
         error_page 404 401 402 408 403 405 500 503 502 504 /error.html;
        }
        location  ~/(admin|master) {
         error_page 404 401 402 408 403 405 500 503 502 504 /error.html;
        }
        # BLOK_URLS - engellenecek ek path'ler sonradan buraya eklenecek
        location /auth/metrics {
          error_page 404 401 402 408 403 405 500 503 502 504 /error.html;
        }
        location /auth/health {
         error_page 404 401 402 408 403 405 500 503 502 504 /error.html;
         }
        location /auth/admin {
             error_page 404 401 402 408 403 405 500 503 502 504 /error.html;
        }
        location /auth {
             error_page 404 401 402 408 403 405 500 503 502 504 /error.html;
        }
        location ^~ /auth/realms/main/ {
            proxy_pass https://backend_individual;
            proxy_http_version 1.1;
            proxy_set_header Connection "keep-alive";
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
            proxy_intercept_errors on;
          if ($is_browser) {
            error_page 404 401 402 408 403 405 500 503 502 504 /error.html;
          }
        }
        location ^~ /auth/realms/comm/ {
            proxy_pass https://backend_commercial;
            proxy_http_version 1.1;
            proxy_set_header Connection "keep-alive";
            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
            proxy_intercept_errors on;
          if ($is_browser) {
            error_page 404 401 402 408 403 405 500 503 502 504 /error.html;
          }
        }
    }
}
